FROM andrius/alpine-ruby

LABEL maintainer="Ruslan Yagudin <r@zoloto585.ru>"

ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME
ADD Gemfile* $APP_HOME/

RUN apk add --no-cache --virtual .build-deps build-base \
    ruby \
    ruby-dev \
    ruby-bundler \
    ruby-json \
    ruby-irb \
    ruby-rake \
    ruby-bigdecimal \
    && gem install bundler -v "1.17.2" \
    && bundle install \
    && apk del .build-deps


ADD . $APP_HOME

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
