global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#otus'
